"""Reporter agent – builds the final markdown report.

Uses anthropic/claude-3-5-sonnet via OpenRouter to generate a polished markdown report.
"""
import json
from typing import List
from models.research import Claim, Source, Contradiction
from services.openrouter import OpenRouterService


class Reporter:
    def __init__(self):
        self.openrouter = OpenRouterService()

    async def report(self, query: str, claims: List[Claim], contradictions: List[Contradiction], sources: List[Source]) -> str:
        # Build context
        sources_text = "\n".join([f"- {s.title} ({s.url}): {s.summary}" for s in sources])
        claims_text = "\n".join([f"- {c.text} (confidence: {c.confidence})" for c in claims])
        contradictions_text = "\n".join([
            f"- {c.claim_a} ↔ {c.claim_b}: {c.explanation}"
            for c in contradictions
        ]) if contradictions else "None detected."

        messages = [
            {
                "role": "system",
                "content": "You are a research reporter. Generate a well-structured markdown report from the research findings. Include sections: Summary, Claims, Sources, Contradictions (if any). Use ## headers."
            },
            {
                "role": "user",
                "content": f"Generate a research report for: {query}\n\nSources:\n{sources_text}\n\nClaims:\n{claims_text}\n\nContradictions:\n{contradictions_text}"
            }
        ]

        response = await self.openrouter.chat("reporting", messages)
        content = response.get("choices", [{}])[0].get("message", {}).get("content", "")

        if content:
            return content

        # Fallback: generate basic markdown
        md = f"# Research Report\n\n**Query**: {query}\n\n## Claims\n"
        for i, claim in enumerate(claims, 1):
            md += f"{i}. {claim.text} (confidence: {claim.confidence:.2f})\n"
        md += "\n## Sources\n"
        for i, src in enumerate(sources, 1):
            md += f"- [{i}] [{src.title}]({src.url})\n"
        if contradictions:
            md += "\n## Contradictions\n"
            for c in contradictions:
                md += f"- {c.claim_a} ↔ {c.claim_b}\n  *{c.explanation}*\n"
        md += "\n---\nGenerated by Lexis AI."
        return md
